version: '3.5'

services:
  database:
    image: mongo:5
    restart: on-failure
    networks:
      - leticia-network
    ports:
      - ${DB_PORT:-3010}:27017
    volumes:
      - ${LETICIA_DB_PATH:-~/leticiaDatabase}:/data/db
  index:
    image: solr:8
    restart: on-failure
    networks:
      - leticia-network
    ports:
      - ${INDEX_PORT:-3011}:8983
    volumes:
      - ${LETICIA_INDEX_PATH:-~/leticiaIndex}:/opt/solr/server/solr/mycores
    entrypoint:
      - solr-precreate
      - ${INDEX_CORE:-leticia}
  webapp:
    build: .
    image: dgacitua/leticia
    restart: on-failure
    networks:
      - leticia-network
    ports:
      - ${WEBAPP_PORT:-3000}:3000
      - ${OPENAPI_PORT:-3001}:3001
    volumes:
      - ${LETICIA_ASSET_PATH:-~/leticiaAssets}:/app/build/assets
    environment:
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
      - MONGODB_DATA_DB=${MONGODB_DATA_DB:-"leticia-data"}
      - MONGODB_USER_DB=${MONGODB_USER_DB:-"leticia-user"}
      - SOLR_HOST=index
      - SOLR_PORT=8983
      - SOLR_CORE=${SOLR_CORE:-leticia}
    links:
      - database
      - index

networks:
  leticia-network:
    name: leticia